replicaCount: 1

image:
  repository: aipyth/hackademy-supabase-app
  tag: "fa533a3"
  port: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: www.my-application.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

configmap:
  NEXT_PUBLIC_SUPABASE_APP_URL: https://pndfgbnxitpxoofuyrlo.supabase.co
  NEXT_PUBLIC_SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYzMDYwMzgzOSwiZXhwIjoxOTQ2MTc5ODM5fQ.5EntK-sXJgcRMsrkKr_TVHpn6VQiYRJPryivRQ7sVWI
secrets-name: fe-app-secrets
