apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: fe-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Chart.Name }}-nextjs
      protocol: TCP
      name: http
  selector:
    app: fe-app
    type: front
